# Generated by Django 6.0 on 2026-01-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.JSONField(blank=True, default=list, help_text='Select available sizes for this product'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_type',
            field=models.CharField(choices=[('jeans', 'Jeans'), ('shirt', 'Shirt'), ('shoes', 'Shoes'), ('one_size', 'One Size'), ('none', 'No Size')], default='none', help_text='Select the type of sizes for this product', max_length=20),
        ),
    ]
